import Head from "next/head";
import {PropsWithChildren} from "react";
import Navbar from "@/components/Navbar/Navbar";


export default function Layout({children}: PropsWithChildren) {
    return <>
        <Head>
            <title>Book shop</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div>
            <header>
                <Navbar/>
            </header>
            <main>
                {children}
            </main>
        </div>
    </>;
}