import Head from 'next/head';
import {Inter} from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import Sidebar from '@/components/Sidebar/Sidebar';
import Slider from "@/components/Slider/Slider";
import Books from "@/components/Books/Books";
import {booksApi, useGetBooksBySubjectQuery} from "@/api/booksApi";
import React, {useEffect, useState} from "react";
import {IBook} from "@/data/types";
import {GetServerSideProps, GetStaticProps, InferGetServerSidePropsType, InferGetStaticPropsType} from "next";

const inter = Inter({subsets: ['latin']});

export const getServerSideProps = (async (params: {subject: string}) => {
    const urlParams = new URLSearchParams();
    urlParams.append("subject", `"subject:${params.subject}"`);
    urlParams.append("pageIndex", "0");
    urlParams.append("maxResults", "6");
    const response = await fetch("https://www.googleapis.com/books/v1/volumes?q=subject:Architecture&startIndex=0&maxResults=6");
    const data: {items: IBook[]} = await response.json();
    return {
        props: {data: data.items}
    }
})

export default function Home({data}: InferGetServerSidePropsType<GetServerSideProps>) {
    const [pageIndex, setPageIndex] = useState(0);


    return (
        <>
            <Head>
                <title>Book shop</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Slider/>
                <section className={styles.books}>
                    <Sidebar/>

                    {data ? <Books books={data}/>:<div className={styles.noContent}>No items found...</div>}
                    <div className={styles.btnWrapper}>
                        <button className={styles.btn} style={{width: "100%"}}>Load more</button>
                    </div>
                </section>
            </main>
        </>
    );
}
